[package]
name = "macros"
version = "0.1.0"
authors = ["Ray Suliteanu <raysuliteanu@gmail.com>"]
description = "Examples of using macros"
keywords = ["proc_macro", "procmacro"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.66"
quote = "1.0.36"
