[package]
name = "rust-flyio-jepsen"
version = "0.1.0"
edition = "2021"

[dependencies]
maelstrom-node = "0.1.6"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
async-trait = "0.1.80"
