[package]
name = "tree-sitter-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-highlight = "0.22.5"
tree-sitter-rust = "0.21.0"
lazy_static = "1.4.0"
